<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Validations.Net\Validations.Net.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\logo.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
        <Link>logo.png</Link>
      </None>
      <None Include="..\..\README.md">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
        <Link>README.md</Link>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ValidatorAttributes\" />
      <Folder Include="Validators\" />
    </ItemGroup>

</Project>
